### ISSUE TITLE
Upload Music Files via FTP/SFTP

### ISSUE THREAD

**Issue by CrAazZyMaN21** [flyth/ts3soundbot#105]
At this moment it is not possible to Upload Music via ftp. It would be a nice idea for Backup and uploading music with a scp command from terminal. Why are you renaming these files?

**Comment by flyth** [comment]
Things are done this way because
a) everything is getting indexed after upload and stored in a database, so that the filesystem becomes virtual, which makes it a lot easier to move files around, have several links to it, etc.
b) the bot has built-in de-duplication based on the files' hash, so it made sense to store it that way directly
c) I don't want to bother with all the file-system name restrictions on the different OSes
d) this also mitigates some security issues by design
e) I don't want the users to encourage to use FTP :) - SFTP is almost always only accessible for the administrator

However: (periodic or triggered) import will at some point be possible (see todo-list), I'm not sure about the export, though.

**Comment by flyth** [comment]
Has to do with #37
