### ISSUE TITLE
Some Bugs/Enhancements

### ISSUE THREAD

**Issue by JBou** [flyth/ts3soundbot#121]
First of all, this is an awesome Music Bot and I would like to thank you for this. Keep up this good work! :+1: 

So, I've found a few bugs:
- The volume slider is not visible on a mobile phone
- After uploading a song you have to reload the page to see it in "All Music"
- The equalizer icon is a bit buggy. I'm playing a radio, but the icon is showing on a folder, and sometimes on a track which is not playing. [Image](http://i.imgur.com/EOvuUDN.png)
- You can upload all types of files on the Upload page. This should be limited to Music files.
- It's not possible to set the privileges on the user accounts page on Google Chrome for Android (maybe a bug with ).

And now some enhancements I would like to see:
- It would be nice to add a button to select all songs in bulk mode
- If the youtube-dl is not set in the config it would be nice if you could download it automatically or at least show a message that we have to download it our self and add the path to the config.
- It would be nice if we could stream a Shout- / Icecast stream from the web panel.
- A feature I would like is to download a whole Soundcloud playlist (it's already possible with youtube-dl, but I've just tried it and got the following error):
```
Unable to download JSON metadata: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))	
```

Regards JBou

**Comment by flyth** [comment]
Thank you very much for your feedback! I'll answer in short to each of the topics you mention:

* I think there's not enough space for the volume slider on a mobile phone. The interface has been optimized for desktops (I've tried to keep as much as possible responsive, though) and I'm not sure if there's enough use on mobile phones so that it'd be worth investing much time into optimizing it
* The upload/refresh thing is not that easy to fix; I'll probably take the big upload-field out there soon, because on every other page it should refresh just fine (upload by directly dragging files onto the filelist/playlist)
* eq-glitch: confirmed, fixed in the next version
* Upload-Limitation: the bot can play everything that ffmpeg can play; if you update other data, it'll be a waste of bandwidth, but not storage, since the file will be dropped if the bot can't handle it. It's much more difficult to figure out what is playable and what not before the actual upload. I'll however include a filter-mechanism later on so that the bot-admin can limit uploads to mime-types.
* privilege on mobile phones should be fixed with the next update. I've also enhanced the difference between active / inactive there.

* bulk-select-all is available by ctrl+a/cmd+a, but there will be another checkbox to click visually with the next update as well
* I'll try to enhance that download-dialog somehow with one of the next updates
* You can add such streams using the "Add URL" button, but I guess you mean either stream without adding (like the !stream-command does) or implementing a browser for shoutcast, which won't be possible due to restrictions of usage on their side (shoutcast), I guess
* downloading playlists is just not yet implemented and I have no ETA on that right now, but it'll come sooner or later

**Comment by JBou** [comment]
Sounds good.
With the "Add URL" button, you mean the "add job" button? I can't find another button called like this. I would like If I could add a mp3 stream from the web panel which is not in the list of dir.xiph.org. Or just to stream music without saving it to disk.
Another nice feature would be, if we could favorite radios so we can find them easier.

**Comment by flyth** [comment]
At the top of the files-list there's a button to add streams called "Add URL" :)

**Comment by JBou** [comment]
Oh, thank you, didn't see it. It's working like a charm :D

**Comment by flyth** [comment]
Most of the list has been implemented / fixed. If you feel there's something missing, please open a new ticket.
