### ISSUE TITLE
X-Server crashes

### ISSUE THREAD

**Issue by lukasbraach** [flyth/ts3soundbot#148]
When I start more than 3 instances, the x-server this is running on crashes instantly. (Before the last update I could only run 2 at the same time). My dedicated server is not the fastest, but should definitively have enough resouces to run 4 TeamSpeak clients simultaniously. Hope you can fix it soon. Great work yet! :+1:

**Comment by flyth** [comment]
I've seen installations with 60 bots running just fine and nobody else did report something like this before, so I'm pretty the problem is on your end and I'm unable to fix anything there. If you think the bot has got something to do with it, at least provide some crash logs / more information. Thanks :)

**Comment by lukasbraach** [comment]
Hey flyth,

I fixed the issue. When I started the X-Server manually, it crashed. When
using your start command it works.

Thanks again for providing such a cool application.

2015-03-23 23:43 GMT+01:00 flyth <notifications@github.com>:
