### ISSUE TITLE
Centos help

### ISSUE THREAD

**Issue by 6xPink** [flyth/ts3soundbot#257]
Hi there I have installed this on centos and get numerous issues such as client issues I was wondering if u can make a guide for centos

That would be much appreciated thanks

**Comment by nrauschcom** [comment]
5 issues below yours is a detailed manual. #249

**Comment by 6xPink** [comment]
Your saying I have to do all this shit that's a lot off work for a music bot

**Comment by 6xPink** [comment]
Plus I'm not that so good at centos wondering if you could kindly help me install this

**Comment by nrauschcom** [comment]
The bot is not intentionally made to support CentOS, so no. If you want to
use it easily, switch to Ubuntu/Debian or Windows.

Plus why are you using CentOS if you're not good at it.. ?

6xPink <notifications@github.com> schrieb am Do., 21. Mai 2015 09:01:

**Comment by 6xPink** [comment]
Because it's the most stable version of linux

**Comment by flyth** [comment]
I doubt that all those steps are necessary - that's why it's not on the wiki, yet. It highly depends on which version you're using, though. EL like CentOS are usually pretty outdated and may cause problems with newer software because of that.

About `most stable version of linux`... It's without doubt one of the most conservative distributions (it only uses proven software / versions - important for most enterprises that have to maintain a lot of systems). But without proper knowledge it's IMHO not more or less *stable* than any other distro :)

So you'll either have to wait for anyone to confirm there's no faster way or come up with a faster way to install it on CentOS, switch your distro, try it on your own or give up on the idea of installing the bot right now - sorry.

**Comment by BlueFreakLP** [comment]
I think the ticket can be closed now. If there are any new suggestions / commets please reopen the Ticket or create a new one.
