### ISSUE TITLE
Queue System & temporary downloads

### ISSUE THREAD

**Issue by mauzao9** [flyth/ts3soundbot#28]
Hello there and thanks for such amazing tool.

So i am wondering, with the ability of multiple people logged in on the web panel, if it was possible to queue actions on song playing? Even on the command !stream and !yt it could simply, most likely via permission (admin to bypass it), queue the action instead of replace what's playing on the moment.

This would be interesting for several people chose and control what's to play!
One other thing that would be interesting, is youtube stream instead of upload, i mean, it may just as normally upload the files to stream it, but, would be like a tempfolder and not add to the main music list. That would help to who wants actually the yt video on the library and who wants just to stream it.

Keep up the good work,
;)

**Comment by flyth** [comment]
Thanks :)
I've actually prepared such a queue but haven't finished it yet due to more important things :) So this is definitely coming.
The same goes for the !yt suggestion; the way you described it is the way I want it to work. But people kept asking a lot for that download feature so I implemented it quick and dirty as it is now to satisfy them for the time being :)

I will keep this open as a reminder to myself :)

**Comment by Niggolo** [comment]
About the queue system, I think is better if it come with votenext or maybe a cooldown for each user so idiots can't spam the bot with dumb music

**Comment by mauzao9** [comment]
Yeah one Queue system may even be controlled on the web-side, a list of "Queued Songs", one admin can cancel any queued song would be interesting in case of spam. But if there's only 1 person requesting songs it would be tricky to control spam, so a way to vote skip the current song may be interesting. :)

**Comment by flyth** [comment]
The initial queue-system will come with the next version.

**Comment by flyth** [comment]
Released. Other behavior than the standard one can be implemented via scripts soon.
