### ISSUE TITLE
Some suggestions, Automatic Start Radio Stations

### ISSUE THREAD

**Issue by capsload** [flyth/ts3soundbot#36]
Would be good if the Bot automatically starts Radio Stations defined if he restarts or gets a URL ping Timeout (when the Radio goes offline for 1-2 minutes some time.)

Multiple Instances, which allows the Bot to connect to more then just one Server at the same time!
(Music choosed will be played on all Servers the same ofc.)

Ability to autoswitch Users to "AFK/AWAY" channels when they have both their Headset/Microphone muted.

**Comment by BlueFreakLP** [comment]
"Multiple Instances, which allows the Bot to connect to more then just one Server at the same time!
(Music choosed will be played on all Servers the same ofc.)"
Check if your clients have the same identity

**Comment by flyth** [comment]
Thanks for your suggestions.

I'm already working on auto-resume when a stream gets disconnected. If shutdown properly (see docs) the bot will start playing what it played before shutdown automatically. But I'll include a "play on start" and "play when idle" as well.

Multiple instances are already possible (to as many servers as you like), although they won't broadcast the same automatically. I've thought about that as well but it's much more complicated (due to how everything is implemented right now), so if at all, this will get implemented much later.

AFK-Management & such should be done through other tools right now. I'm focusing on getting all music-related topics to work stable before I think about implementing other "services" :)

**Comment by capsload** [comment]
Looking forward for this auto-start feature <3.

**Comment by MrZhuliK** [comment]
Thanks for bot!
Autoplay very necessary thing, and the need not only autorun play the radio or music when a stream gets disconnected, but also to automatically connect to the teamspeak server including the loss of communication with them or reboot OS system.
Sorry for my english :)

**Comment by flyth** [comment]
Has been implemented and published.
