### ISSUE TITLE
Can't bind permissions to group

### ISSUE THREAD

**Issue by DerEnderKeks** [flyth/ts3soundbot#373]
I want to use the server group feature, but it's not working.

I created a user and added server group ID 8 (my guest group). My bot has the permissions b_virtualserver_servergroup_client_list, b_virtualserver_servergroup_list and some other default permissions. But alway when i try to use a command with the guest group it say "< !play *** > Command ignored, user unknown." in the log.
I don't know what i could do.. may you can help me :)

**Comment by kamikatze13** [comment]
have a similar issue
create a new server group, add the server group id to an account at the "user account" bot page
in a running instance, assign the server group to a not registered user - commands work
now restart the bot - suddenly the commands are no longer accepted
the workaround is to remove a user from the server group and re-add him - commands working again

seems like the bot is not recognizing server group ids after a restart
looks like a bug and defeats the purpose of having server groups instead of user registration

**Comment by flyth** [comment]
It just takes up to a few minutes for the bot to get information about all server groups. After that initial phase is done, everything should be recognized again.

**Comment by DerEnderKeks** [comment]
Today I had make another try and now it works! (I looked into the server-chat log in the data/ts3 folder. There was some permission errors, but now I gave the bot the correct permission(b_virtualserver_servergroup_client_list) and I removed the flood protection)

**Comment by flyth** [comment]
This will be even more fine-tuned in the next release.
